import { Module, Global } from '@nestjs/common';
import { MongooseModule } from '@nestjs/mongoose';
import { ConfigModule, ConfigService } from '@nestjs/config';
import { DataStoreService } from './data-store.service';
import {
  User, UserSchema,
  Session, SessionSchema,
  Profile, ProfileSchema,
  Skill, SkillSchema,
  SkillEvidence, SkillEvidenceSchema,
  UserSkill, UserSkillSchema,
  Career, CareerSchema,
  CareerGoal, CareerGoalSchema,
  CareerPath, CareerPathSchema,
  CareerRecommendation, CareerRecommendationSchema,
  SkillGap, SkillGapSchema,
  Company, CompanySchema,
  Job, JobSchema,
  JobRequirement, JobRequirementSchema,
  JobApplication, JobApplicationSchema,
  SavedJob, SavedJobSchema,
  CandidateMatch, CandidateMatchSchema,
  Shortlist, ShortlistSchema,
  HiringPipeline, HiringPipelineSchema,
  Course, CourseSchema,
  LearningResource, LearningResourceSchema,
  SavedResource, SavedResourceSchema,
  Cohort, CohortSchema,
  Enrollment, EnrollmentSchema,
  LearningProgress, LearningProgressSchema,
  Roadmap, RoadmapSchema,
  Assessment, AssessmentSchema,
  AssessmentAttempt, AssessmentAttemptSchema,
  Project, ProjectSchema,
  ProjectSubmission, ProjectSubmissionSchema,
  ProjectTask, ProjectTaskSchema,
  CodeReview, CodeReviewSchema,
  Portfolio, PortfolioSchema,
  Achievement, AchievementSchema,
  Certificate, CertificateSchema,
  GitHubConnection, GitHubConnectionSchema,
  Interview, InterviewSchema,
  InterviewSession, InterviewSessionSchema,
  InterviewFeedback, InterviewFeedbackSchema,
  Notification, NotificationSchema,
  Conversation, ConversationSchema,
  Message, MessageSchema,
  AnalyticsEvent, AnalyticsEventSchema,
  AIUsage, AIUsageSchema,
  AuditLog, AuditLogSchema,
  Subscription, SubscriptionSchema,
  KnowledgeDocument, KnowledgeDocumentSchema,
  KnowledgeChunk, KnowledgeChunkSchema,
} from './schemas';

const FEATURE_SCHEMAS = [
  { name: User.name, schema: UserSchema },
  { name: Session.name, schema: SessionSchema },
  { name: Profile.name, schema: ProfileSchema },
  { name: Skill.name, schema: SkillSchema },
  { name: SkillEvidence.name, schema: SkillEvidenceSchema },
  { name: UserSkill.name, schema: UserSkillSchema },
  { name: Career.name, schema: CareerSchema },
  { name: CareerGoal.name, schema: CareerGoalSchema },
  { name: CareerPath.name, schema: CareerPathSchema },
  { name: CareerRecommendation.name, schema: CareerRecommendationSchema },
  { name: SkillGap.name, schema: SkillGapSchema },
  { name: Company.name, schema: CompanySchema },
  { name: Job.name, schema: JobSchema },
  { name: JobRequirement.name, schema: JobRequirementSchema },
  { name: JobApplication.name, schema: JobApplicationSchema },
  { name: SavedJob.name, schema: SavedJobSchema },
  { name: CandidateMatch.name, schema: CandidateMatchSchema },
  { name: Shortlist.name, schema: ShortlistSchema },
  { name: HiringPipeline.name, schema: HiringPipelineSchema },
  { name: Course.name, schema: CourseSchema },
  { name: LearningResource.name, schema: LearningResourceSchema },
  { name: SavedResource.name, schema: SavedResourceSchema },
  { name: Cohort.name, schema: CohortSchema },
  { name: Enrollment.name, schema: EnrollmentSchema },
  { name: LearningProgress.name, schema: LearningProgressSchema },
  { name: Roadmap.name, schema: RoadmapSchema },
  { name: Assessment.name, schema: AssessmentSchema },
  { name: AssessmentAttempt.name, schema: AssessmentAttemptSchema },
  { name: Project.name, schema: ProjectSchema },
  { name: ProjectSubmission.name, schema: ProjectSubmissionSchema },
  { name: ProjectTask.name, schema: ProjectTaskSchema },
  { name: CodeReview.name, schema: CodeReviewSchema },
  { name: Portfolio.name, schema: PortfolioSchema },
  { name: Achievement.name, schema: AchievementSchema },
  { name: Certificate.name, schema: CertificateSchema },
  { name: GitHubConnection.name, schema: GitHubConnectionSchema },
  { name: Interview.name, schema: InterviewSchema },
  { name: InterviewSession.name, schema: InterviewSessionSchema },
  { name: InterviewFeedback.name, schema: InterviewFeedbackSchema },
  { name: Notification.name, schema: NotificationSchema },
  { name: Conversation.name, schema: ConversationSchema },
  { name: Message.name, schema: MessageSchema },
  { name: AnalyticsEvent.name, schema: AnalyticsEventSchema },
  { name: AIUsage.name, schema: AIUsageSchema },
  { name: AuditLog.name, schema: AuditLogSchema },
  { name: Subscription.name, schema: SubscriptionSchema },
  { name: KnowledgeDocument.name, schema: KnowledgeDocumentSchema },
  { name: KnowledgeChunk.name, schema: KnowledgeChunkSchema },
];

@Global()
@Module({
  imports: [
    MongooseModule.forRootAsync({
      imports: [ConfigModule],
      inject: [ConfigService],
      useFactory: (config: ConfigService) => {
        const uri = config.get<string>('MONGODB_URI') || 'mongodb://127.0.0.1:27017/skillora';
        return {
          uri,
        };
      },
    }),
    MongooseModule.forFeature(FEATURE_SCHEMAS),
  ],
  providers: [DataStoreService],
  exports: [MongooseModule, DataStoreService],
})
export class DatabaseModule {}
