// Skillora Standard Taxonomy & Reference Catalogs (Production-Safe)

export const SEED_COMPANIES = [
  {
    id: 'comp-1',
    name: 'TechScale AI',
    logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=100&auto=format&fit=crop&q=80',
    domain: 'techscale.ai',
    industry: 'Generative AI & Enterprise SaaS',
    size: '250-500',
    location: 'San Francisco, CA (Remote)',
    verified: true,
    about: 'TechScale AI builds enterprise-grade foundation model workflows and retrieval-augmented systems.',
    openJobsCount: 6,
  },
  {
    id: 'comp-2',
    name: 'QuantumData Labs',
    logo: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=100&auto=format&fit=crop&q=80',
    domain: 'quantumdata.ai',
    industry: 'Big Data & Real-time Analytics',
    size: '100-250',
    location: 'New York, NY (Hybrid)',
    verified: true,
    about: 'Pioneering high-throughput distributed vector search and predictive analytics for modern enterprises.',
    openJobsCount: 4,
  },
  {
    id: 'comp-3',
    name: 'CyberShield Corp',
    logo: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=100&auto=format&fit=crop&q=80',
    domain: 'cybershield.io',
    industry: 'Cybersecurity & Zero-Trust Infrastructure',
    size: '500-1000',
    location: 'Austin, TX (Remote)',
    verified: true,
    about: 'Automated threat detection and secure container runtime security monitoring.',
    openJobsCount: 5,
  },
  {
    id: 'comp-4',
    name: 'Apex Cloud Solutions',
    logo: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=100&auto=format&fit=crop&q=80',
    domain: 'apexcloud.net',
    industry: 'Cloud Native & Kubernetes Infrastructure',
    size: '50-100',
    location: 'Seattle, WA (Remote)',
    verified: true,
    about: 'Helping global engineering teams scale multi-cloud Kubernetes clusters with automated observability.',
    openJobsCount: 3,
  },
];

export const SEED_SKILLS = [
  { id: 'skl-1', name: 'TypeScript', category: 'Programming', subcategory: 'Web', difficulty: 'Intermediate', prerequisites: ['JavaScript'], relatedSkills: ['JavaScript', 'Node.js'], industryDemandScore: 96, marketTrend: 'High' },
  { id: 'skl-2', name: 'JavaScript', category: 'Programming', subcategory: 'Web', difficulty: 'Beginner', prerequisites: [], relatedSkills: ['TypeScript', 'HTML5'], industryDemandScore: 98, marketTrend: 'Steady' },
  { id: 'skl-3', name: 'Python', category: 'Programming', subcategory: 'AI/Backend', difficulty: 'Beginner', prerequisites: [], relatedSkills: ['Data Science', 'FastAPI'], industryDemandScore: 99, marketTrend: 'Exploding' },
  { id: 'skl-4', name: 'React', category: 'Frontend', subcategory: 'UI Library', difficulty: 'Intermediate', prerequisites: ['JavaScript'], relatedSkills: ['Next.js', 'Redux'], industryDemandScore: 97, marketTrend: 'High' },
  { id: 'skl-5', name: 'Next.js', category: 'Frontend', subcategory: 'Meta-Framework', difficulty: 'Intermediate', prerequisites: ['React', 'TypeScript'], relatedSkills: ['React', 'SSR'], industryDemandScore: 95, marketTrend: 'Exploding' },
  { id: 'skl-6', name: 'NestJS', category: 'Backend', subcategory: 'Framework', difficulty: 'Intermediate', prerequisites: ['TypeScript', 'Node.js'], relatedSkills: ['Node.js', 'Express'], industryDemandScore: 91, marketTrend: 'Exploding' },
  { id: 'skl-7', name: 'Node.js', category: 'Backend', subcategory: 'Runtime', difficulty: 'Intermediate', prerequisites: ['JavaScript'], relatedSkills: ['Express', 'NestJS'], industryDemandScore: 94, marketTrend: 'Steady' },
  { id: 'skl-8', name: 'MongoDB', category: 'Database', subcategory: 'Document NoSQL', difficulty: 'Beginner', prerequisites: [], relatedSkills: ['Mongoose', 'Database Design'], industryDemandScore: 90, marketTrend: 'Steady' },
  { id: 'skl-9', name: 'PostgreSQL', category: 'Database', subcategory: 'Relational SQL', difficulty: 'Intermediate', prerequisites: ['SQL'], relatedSkills: ['SQL', 'Prisma'], industryDemandScore: 96, marketTrend: 'High' },
  { id: 'skl-10', name: 'RAG (Retrieval-Augmented Generation)', category: 'AI/ML', subcategory: 'LLM Systems', difficulty: 'Advanced', prerequisites: ['Vector Embeddings', 'Prompt Engineering'], relatedSkills: ['Qdrant', 'Gemini AI API'], industryDemandScore: 99, marketTrend: 'Exploding' },
  { id: 'skl-11', name: 'Gemini AI API', category: 'AI/ML', subcategory: 'LLM Integration', difficulty: 'Intermediate', prerequisites: ['REST API Design'], relatedSkills: ['Prompt Engineering', 'RAG'], industryDemandScore: 95, marketTrend: 'Exploding' },
  { id: 'skl-12', name: 'Docker', category: 'DevOps', subcategory: 'Containers', difficulty: 'Intermediate', prerequisites: ['Linux'], relatedSkills: ['Kubernetes', 'CI/CD'], industryDemandScore: 95, marketTrend: 'Steady' },
  { id: 'skl-13', name: 'System Design', category: 'Architecture', subcategory: 'Distributed Systems', difficulty: 'Advanced', prerequisites: ['Databases', 'Networking'], relatedSkills: ['Microservices', 'Scalability'], industryDemandScore: 97, marketTrend: 'High' },
];

export const SEED_JOBS = [
  {
    id: 'job-1',
    companyId: 'comp-1',
    companyName: 'TechScale AI',
    companyLogo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=100&auto=format&fit=crop&q=80',
    title: 'Full-Stack AI Systems Engineer',
    department: 'Core Engineering',
    location: 'San Francisco, CA (Remote)',
    mode: 'remote',
    salaryRange: '$130,000 - $165,000',
    experienceLevel: 'Mid',
    requiredSkills: ['TypeScript', 'Next.js', 'NestJS', 'RAG', 'Gemini AI', 'MongoDB'],
    preferredSkills: ['Docker', 'Qdrant', 'Tailwind CSS'],
    description: 'Join TechScale AI to architect and scale real-time AI-powered workforce intelligence and generative enterprise workflows.',
    responsibilities: [
      'Collaborate with cross-functional AI teams to deliver production-grade workforce intelligence features.',
      'Maintain 99.9% uptime across critical customer-facing microservices and API gateways.',
      'Conduct comprehensive peer code reviews and contribute to architecture design documentation.',
    ],
    requirements: [
      'Demonstrated experience building and maintaining web applications in production.',
      'Strong foundation in distributed systems, asynchronous computing, and relational/document databases.',
      'Excellent communication skills and eagerness to continuously learn new technologies.',
    ],
    postedAt: new Date().toISOString().split('T')[0],
    applicantsCount: 18,
  },
  {
    id: 'job-2',
    companyId: 'comp-1',
    companyName: 'TechScale AI',
    companyLogo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=100&auto=format&fit=crop&q=80',
    title: 'Senior Backend Engineer (NestJS / TypeScript)',
    department: 'Platform Backend',
    location: 'San Francisco, CA (Remote)',
    mode: 'remote',
    salaryRange: '$140,000 - $175,000',
    experienceLevel: 'Senior',
    requiredSkills: ['NestJS', 'TypeScript', 'MongoDB', 'REST API', 'Docker', 'Redis'],
    preferredSkills: ['Kafka', 'Microservices', 'Kubernetes'],
    description: 'Lead the architecture of our distributed microservices layer handling millions of daily inference calls.',
    responsibilities: [
      'Architect robust, scalable backends with NestJS and MongoDB.',
      'Implement strict authentication, rate limiting, and observability pipelines.',
    ],
    requirements: [
      '5+ years experience in enterprise backend engineering.',
      'Deep knowledge of TypeScript and distributed systems architecture.',
    ],
    postedAt: new Date().toISOString().split('T')[0],
    applicantsCount: 12,
  },
  {
    id: 'job-3',
    companyId: 'comp-2',
    companyName: 'QuantumData Labs',
    companyLogo: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=100&auto=format&fit=crop&q=80',
    title: 'RAG & Retrieval Systems Specialist',
    department: 'AI Research',
    location: 'New York, NY (Hybrid)',
    mode: 'hybrid',
    salaryRange: '$145,000 - $185,000',
    experienceLevel: 'Senior',
    requiredSkills: ['Python', 'Qdrant', 'Vector Embeddings', 'RAG', 'Prompt Engineering'],
    preferredSkills: ['FastAPI', 'LangChain', 'BM25'],
    description: 'Develop state-of-the-art hybrid vector retrieval systems with sub-50ms latency over billions of document vectors.',
    responsibilities: [
      'Design retrieval algorithms and semantic re-ranking systems.',
      'Build zero-hallucination citation engines for enterprise documents.',
    ],
    requirements: [
      'Strong background in vector search, embeddings, and generative AI models.',
    ],
    postedAt: new Date().toISOString().split('T')[0],
    applicantsCount: 9,
  },
];

export const SEED_ASSESSMENTS = [
  {
    id: 'asm-1',
    title: 'Advanced TypeScript & Enterprise Architecture',
    category: 'Programming',
    skillName: 'TypeScript',
    difficulty: 'Intermediate',
    durationMinutes: 25,
    passingScore: 75,
    questionsCount: 3,
    questions: [
      {
        id: 'q1',
        type: 'mcq',
        prompt: 'In TypeScript, what is the exact difference between type and interface when designing extensible open models?',
        options: [
          'Interfaces allow declaration merging, while type aliases cannot be merged after definition.',
          'Type aliases support declaration merging, while interfaces are closed.',
          'There is no difference; they compile to identical runtime JavaScript classes.',
          'Interfaces can only extend classes, while types cannot.',
        ],
        correctAnswer: 0,
        explanation: 'TypeScript interfaces are open and support declaration merging, making them ideal for library API contracts and public schemas.',
      },
      {
        id: 'q2',
        type: 'mcq',
        prompt: 'How does the "satisfies" operator introduced in TypeScript 4.9 improve on type assertions (as Type)?',
        options: [
          'It forces the variable to be typed as any.',
          'It validates that an expression matches a type without overriding or widening the inferred specific literal type.',
          'It disables runtime bounds checking.',
          'It generates runtime type validation code in the output JS bundle.',
        ],
        correctAnswer: 1,
        explanation: 'The satisfies operator verifies type conformity while preserving specific literal member types and autocompletion.',
      },
      {
        id: 'q3',
        type: 'coding',
        prompt: 'Write a generic TypeScript type "DeepReadonly<T>" that recursively marks all properties of object T as readonly.',
        starterCode: 'type DeepReadonly<T> = {\n  readonly [P in keyof T]: T[P] extends object ? DeepReadonly<T[P]> : T[P];\n};',
        correctAnswer: 'DeepReadonly',
        explanation: 'Recursive mapped types traverse nested dictionary structures to apply readonly immutability at every level.',
      },
    ],
  },
  {
    id: 'asm-2',
    title: 'NestJS Architecture & Dependency Injection',
    category: 'Backend',
    skillName: 'NestJS',
    difficulty: 'Intermediate',
    durationMinutes: 20,
    passingScore: 80,
    questionsCount: 2,
    questions: [
      {
        id: 'q1',
        type: 'mcq',
        prompt: 'Why should request-scoped providers be used with caution in high-throughput NestJS APIs?',
        options: [
          'They cause memory leaks in JavaScript garbage collector.',
          'They force the entire dependency subtree to be re-instantiated on every incoming HTTP request, impacting latency.',
          'They disable HTTP request logging.',
          'They are incompatible with TypeScript strict mode.',
        ],
        correctAnswer: 1,
        explanation: 'Request-scoped providers bubble up the dependency chain, forcing re-instantiation of dependent singletons for every single HTTP request.',
      },
    ],
  },
];

export const SEED_COURSES = [
  {
    id: 'crs-1',
    title: 'Full-Stack AI Architecture Masterclass',
    educatorName: 'Dr. Alan Mitchell',
    domain: 'Full-Stack AI',
    level: 'Advanced',
    rating: 4.9,
    enrolledLearners: 142,
    modulesCount: 6,
    description: 'Master enterprise-grade generative AI full-stack applications with NestJS, Next.js, and Qdrant vector retrieval.',
  },
  {
    id: 'crs-2',
    title: 'Modern TypeScript & Resilient Microservices',
    educatorName: 'Prof. Sumaiya Begum',
    domain: 'Backend Engineering',
    level: 'Intermediate',
    rating: 4.8,
    enrolledLearners: 215,
    modulesCount: 5,
    description: 'Build production-ready backends with strict typing, schema validation, and zero-trust authentication.',
  },
];

export const SEED_PROJECTS = [
  {
    id: 'prj-1',
    title: 'Autonomous RAG Knowledge Assistant',
    category: 'AI/ML & Backend',
    difficulty: 'Advanced',
    targetSkills: ['RAG', 'Gemini AI', 'Qdrant', 'NestJS', 'TypeScript'],
    brief: 'Build an enterprise document intelligence pipeline with chunking, citation mapping, and vector search.',
    architecture: 'Client -> Next.js -> NestJS API Gateway -> Qdrant Vector Collection -> Gemini Flash Grounded Synthesis',
    milestones: [
      'Milestone 1: Environment initialization and database schema modeling',
      'Milestone 2: Core business logic, unit tests, and validation pipeline',
      'Milestone 3: Performance optimization, containerization, and automated CI pipeline',
    ],
    techStack: ['NestJS', 'Next.js', 'Qdrant', 'Gemini AI', 'MongoDB'],
    estimatedHours: 30,
    starterGithubRepo: 'https://github.com/skillora-projects/rag-assistant',
  },
  {
    id: 'prj-2',
    title: 'Distributed Real-Time Telemetry Dashboard',
    category: 'Full-Stack',
    difficulty: 'Intermediate',
    targetSkills: ['Next.js', 'React', 'WebSockets', 'Tailwind CSS', 'Recharts'],
    brief: 'Architect a 60fps real-time metrics visualizer with dynamic threshold alerts and data streaming.',
    architecture: 'Simulated IoT Feed -> WebSocket Gateway -> React State Store -> Canvas/SVG Rendered Recharts',
    milestones: [
      'Milestone 1: WebSocket connection management and resilience',
      'Milestone 2: Real-time chart rendering and threshold filtering',
      'Milestone 3: Export telemetry reports and mobile responsive optimization',
    ],
    techStack: ['Next.js', 'React', 'Tailwind CSS', 'WebSockets'],
    estimatedHours: 20,
    starterGithubRepo: 'https://github.com/skillora-projects/telemetry-dashboard',
  },
];

// Reference catalogs only
